name: leapfrog-fault-models
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pyproj
  - numpy >= 1.18.1
  - geopandas >= 0.6.1
  - matplotlib >= 3.1.1
  - ipython >= 7.9.0
  - scipy >= 1.3.1
  - rasterio >= 1.1.5
  - pip
  - git >= 2.21.1
  - pip:
    - ./fault_mesh_building
    - git+https://github.com/GNS-Science/eq-fault-geom
