name: leapfrog-fault-models
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyproj
  - numpy >= 1.18.1
  - geopandas >= 0.11.1
  - matplotlib >= 3.1.1
  - ipython >= 7.9.0
  - scipy >= 1.15.2
  - rasterio >= 1.1.5
  - pip
  - git >= 2.21.1
  - sphinx
  - sphinx-autoapi
  - myst-nb
  - notebook
  - pip:
    - ./tectonic_fault_mesh_tools
    - meshio
    - sphinx-rtd-theme
