name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout github repo including lfs files
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        channels: conda-forge
        activate-environment: leapfrog-fault-models
        environment-file: environment.yml
        use-mamba: true
        auto-activate-base: false

    - run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Build and Commit
      uses: andy22b/pages@v2
      with:
        documentation_path: docs

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
