name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:

    - name: Checkout github repo including lfs files
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0

    - name: Cache conda
      uses: actions/cache@v2
      env:
        cache-name: cache-conda-env
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.cache-name }}-${{ hashFiles('environment.yml') }}

    - name: Install package dependencies with setup-miniconda@v2
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: leapfrog-fault-models
        environment-file: environment.yml
        auto-activate-base: false
        channels: conda-forge
        channel-priority: strict
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
    - run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show

    - name: Build and Commit
      uses: andy22b/pages@v2
      with:
        documentation_path: docs

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
